2024-09-17 15:13:48,323 ERROR frappe New Exception collected with id: 2024-09-17 15:13:48.191143-127.0.0.1-daa
Site: saas_site
Form Dict: {'cmd': 'fox_erp_saas.api.get_employee_list'}
2024-09-17 15:15:27,327 ERROR frappe New Exception collected with id: 2024-09-17 15:15:27.314903-127.0.0.1-c01
Site: saas_site
Form Dict: {'cmd': 'fox_erp_saas.api.get_employee_list'}
2024-09-19 13:56:36,086 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'actions', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/actions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 13:57:01,007 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'actions', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/actions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 13:57:59,123 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'actions', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/actions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 13:58:04,505 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'actions', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/actions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 13:58:21,127 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'forhrpage', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/forhrpage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 13:58:41,301 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'forhrpage', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/forhrpage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 13:58:47,600 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'forhrpage', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/forhrpage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 13:59:06,829 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'forhrpage', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/forhrpage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 14:00:09,833 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'forhrpage', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/forhrpage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 14:00:16,492 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'forhrpage', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/forhrpage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 14:00:38,497 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'forhrpage', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/forhrpage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2024-09-19 15:00:30,928 ERROR frappe Could not take error snapshot: characters_written
Site: saas_site
Form Dict: {'name': 'actions', 'cmd': 'frappe.desk.desk_page.getpage'}
Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 31, in getpage
    doc = get(page)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/desk/desk_page.py", line 14, in get
    page.load_assets()
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/core/doctype/page/page.py", line 134, in load_assets
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kanchanfrappe/forerpsaas_bench/apps/fox_erp_saas/fox_erp_saas/fox_erp_saas/page/actions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 60, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/kanchanfrappe/forerpsaas_bench/apps/frappe/frappe/utils/error.py", line 155, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
